"""alter_frequencia

Revision ID: 3faef9c9e535
Revises: caa34fa97c91
Create Date: 2024-03-25 17:38:24.295401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faef9c9e535'
down_revision = 'caa34fa97c91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frequencias', sa.Column('hora', sa.String(), nullable=True))
    op.alter_column('frequencias', 'data',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequencias', 'data',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('frequencias', 'hora')
    # ### end Alembic commands ###
