"""pop

Revision ID: caa34fa97c91
Revises: 95965f7dec90
Create Date: 2024-03-14 16:42:04.893285

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "caa34fa97c91"
down_revision = "95965f7dec90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from app.db import pop_db

    pop_db()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
